SELECT * FROM Fashion;
SELECT TOP(10) * FROM Fashion;
SELECT TOP (10) Colour, Brand FROM Fashion
SELECT Colour FROM Fashion
SELECT DISTINCT (Colour) FROM Fashion

--TOP 5 AVG RATING BASE ON COLOUR
SELECT Colour, [Avg Rating]
FROM Fashion
ORDER BY [Avg Rating] DESC
OFFSET 0 ROWS
FETCH FIRST 5 ROWS ONLY;

--TOP TEN MOST EXPENSIVE COLOUR
SELECT COLOUR, PRICE
FROM Fashion
ORDER BY PRICE DESC
OFFSET 0 ROWS
FETCH FIRST 10 ROW ONLY;

SELECT TOP 10 Colour, MAX(Price) AS MaxPrice
FROM Fashion
GROUP BY Colour
ORDER BY MaxPrice DESC;


--MOST EXPENSIVE BRAND
SELECT BRAND, PRICE
FROM Fashion
ORDER BY PRICE DESC
OFFSET 0 ROWS
FETCH FIRST 10 ROWS ONLY;

-- 10 TOP MOST RATED COLOUR
SELECT TOP 10 Colour, COUNT(*) AS RatingCount
FROM Fashion
GROUP BY Colour
ORDER BY RatingCount DESC;

-- TOP 10 MOST RATED BRAND
SELECT TOP 10 Brand, COUNT (*) AS RatingCount
FROM Fashion
GROUP BY Brand
ORDER BY RatingCount DESC;

-- TOP 10 MOST PURCHASED BRAND
SELECT TOP 10 Brand, COUNT(*) AS RatingCount
FROM Fashion
GROUP BY Brand
ORDER BY RatingCount desc;

SELECT TOP 1 BRAND, COUNT(*) AS MostPurchased
FROM Fashion
GROUP BY Brand
ORDER BY MostPurchased desc;

